CREATE PROCEDURE InsertCompanyRevenue
(
    @REPORT_DATE VARCHAR(7),
    @DATA_DATE_TIME VARCHAR(5),
    @CO_NO VARCHAR(10),
    @COMPANY_NAME NVARCHAR(100),
    @INDUSTRY NVARCHAR(50),
    @REVENUE_FOR_THE_MONTH DECIMAL(18, 2),
    @REVENUE_LAST_MONTH DECIMAL(18, 2),
    @REVENUE_FOR_THE_MONTH_LAST_YEAR DECIMAL(18, 2),
    @LAST_MONTH_CHANGE DECIMAL(18, 2),
    @YEARLY_SAME_MONTH_CHANGE DECIMAL(18, 2),
    @GRAND_TOTAL_REVENUE_FOR_THE_MONTH DECIMAL(18, 2),
    @GRAND_TOTAL_REVENUE_LAST_YEAR DECIMAL(18, 2),
    @GRAND_TOTAL_PRIOR_PERIOD_CHANGE DECIMAL(18, 2),
    @REMARK NVARCHAR(100)
)
AS
BEGIN
    INSERT INTO CompanyRevenue
    (
        REPORT_DATE,
        DATA_DATE_TIME,
        CO_NO,
        COMPANY_NAME,
        INDUSTRY,
        OPERATING_INCOME_REVENUE_FOR_THE_MONTH,
        OPERATING_INCOME_REVENUE_LAST_MONTH,
        OPERATING_INCOME_REVENUE_FOR_THE_MONTH_LAST_YEAR,
        OPERATING_INCOME_LAST_MONTH_CHANGE,
        OPERATING_INCOME_YEARLY_SAME_MONTH_CHANGE,
        GRAND_TOTAL_OPERATING_INCOME_REVENUE_FOR_THE_MONTH,
        GRAND_TOTAL_OPERATING_INCOME_REVENUE_LAST_YEAR,
        GRAND_TOTAL_OPERATING_INCOME_PRIOR_PERIOD_CHANGE,
        REMARK
    )
    VALUES
    (
        @REPORT_DATE,
        @DATA_DATE_TIME,
        @CO_NO,
        @COMPANY_NAME,
        @INDUSTRY,
        @REVENUE_FOR_THE_MONTH ,
		@REVENUE_LAST_MONTH ,
		@REVENUE_FOR_THE_MONTH_LAST_YEAR,
		@LAST_MONTH_CHANGE,
		@YEARLY_SAME_MONTH_CHANGE,
		@GRAND_TOTAL_REVENUE_FOR_THE_MONTH,
		@GRAND_TOTAL_REVENUE_LAST_YEAR,
		@GRAND_TOTAL_PRIOR_PERIOD_CHANGE,
		@REMARK 
    );
END;