/* tslint:disable */
/* eslint-disable */
/**
 * Gov_ListedCompany_API
 * No description provided (generated by Swagger Codegen https://github.com/swagger-api/swagger-codegen)
 *
 * OpenAPI spec version: 1.0
 * 
 *
 * NOTE: This class is auto generated by the swagger code generator program.
 * https://github.com/swagger-api/swagger-codegen.git
 * Do not edit the class manually.
 */

 /**
 * 
 *
 * @export
 * @interface OperatingIncomeVo
 */
export interface OperatingIncomeVo {

    /**
     * @type {string}
     * @memberof OperatingIncomeVo
     */
    reportDate?: string | null;

    /**
     * @type {string}
     * @memberof OperatingIncomeVo
     */
    dataDateTime?: string | null;

    /**
     * @type {string}
     * @memberof OperatingIncomeVo
     */
    coNo?: string | null;

    /**
     * @type {string}
     * @memberof OperatingIncomeVo
     */
    companyName?: string | null;

    /**
     * @type {string}
     * @memberof OperatingIncomeVo
     */
    industry?: string | null;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    revenueForTheMonth?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    revenueLastMonth?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    revenueForTheMonthLastYear?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    lastMonthChange?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    yearlySameMonthChange?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    grandTotalRevenueForTheMonth?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    grandTotalRevenueLastYear?: number;

    /**
     * @type {number}
     * @memberof OperatingIncomeVo
     */
    grandTotalPriorPeriodChange?: number;

    /**
     * @type {string}
     * @memberof OperatingIncomeVo
     */
    remark?: string | null;
}
